Optimize word splitter with state machine, replacing regex
wbrown/gpt_bpe pull request #58
Opened 2024-11-25 17:00 UTC by Rexwang8

2024-12-12 22:18 UTC, sangstar requested changes
Looks like a very ambitious and cool feature! A few requests to make sure this code is clean and idiomatic.

2024-12-12 22:18 UTC, sangstar commented on gpt_bpe.go
> +			runeAccumulator = runeLine
This interplay between `runeLine` and `runeAccumulator` is pretty confusing. Looking at this at its face, the code is saying

- `runeLine` can be a slice of `runeAccumulator`
- `runeLine` can be a copy of `runeAccumulator`
- `runeAccumulator` is always eventually a copy of `runeLine`

Is there some way to make this less confusing?

2024-12-12 22:18 UTC, sangstar commented on gpt_bpe.go
> +			if useDefaultRegexPackage && encoder.pattern.String() != "" {
This is fine as is, but you might consider doing something like this, and then not having to have a comment explaining it:

```suggestion
                         regexNotRecognized := useDefaultRegexPackage && encoder.pattern.String() != ""
			if regexNotRecognized {
```

2024-12-12 22:18 UTC, sangstar commented on runetree.go
> +	isContractionTree bool               // Whether this node is a contraction tree
Once again this formatting stuff is puzzling.

2024-12-12 22:18 UTC, sangstar commented on runetree.go
> +				isContractionTree: node.isContractionTree,
Formatting.

2024-12-12 22:18 UTC, sangstar commented on runetree.go
> +				)
Formatting.

2024-12-12 22:18 UTC, sangstar commented on runetree.go
> +func ContractionsTree() *RuneNode {
Slight nitpick, but the wording of this function being `ContractionsTree` sounds like it ought to be a struct, and it's a bit awkward that it takes no arguments. It maybe would warrant its own struct with a pointer to a `RuneNode` struct, and this function could be called `NewContractionsTreeFromDefaults` or something. I don't understand the underlying implementation here though so take this with a grain of salt. Just purely from an idioms perspective. Go's function naming idioms are fairly specific, which is why this pops out.

2025-01-08 17:50 UTC, sangstar reviewed
Great job! Some comments that are mostly nitpicks and good just to document. Once these are resolved I'll approve this. 

The only thing I'll mention is that `traverseRegexTree` is doing an enormous amount of heavy lifting, and would benefit significantly from modularizing in to small functions. I understand if you're concerned about function call overhead being a potential bottleneck in this case (although if they're small enough your compiler should still inline it), so at the very least I would very heavily comment this for each group-able code chunk.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +}
This is not a tuple in the traditional sense because it has homogenous data.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +}
I'd be surprised if this wasn't an unnecessary bottleneck. You're allocating a struct for every pair of runes, when a simple array could do where you just are careful with indexing it, allocating just one.

That being said, profiling doesn't seem to show this as slowing anything down, so take this with a grain of salt.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +	// Create the root node
Nitpick, but these docstrings are not idiomatic. If they're done idiomatically, docs can be automatically generated for them.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +		flags:       int(AST.Flags),
Why do you cast this to an integer rather than keeping it? Keep it as an enum.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +func (runeTree *RegexNode) createTree(AST *syntax.Regexp, ASTPath []string) {
I really do not recommend calling your receiver `runeTree`. This note only adds confusion with the receiver for `RuneNode` being also called `runeTree`, and usually struct receivers are abbreviated anyway, so it would be `rt` or something. These are different structs and as such really shouldn't be taking the same name for the receiver.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +			terminal:    sub.Op == syntax.OpCharClass,
The assumption here is that termination always is from a `syntax.OpCharClass` op. Why is this?

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +}
```suggestion
func (runeTree *RegexNode) String() string {
	// Print the tree
	sb := strings.Builder{}
	runeTree.string(0, &sb)
	return sb.String()
}
```

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +	copy(pathCopy, currentPath)
Another slight nitpick here. Take with a grain of salt as profiling looks good. 

Instead of `copy`ing, you could've also created `pathCopy` with something like:

```
		pathCopy := append([]int{}, currentPath...)
		pathCopy = append(pathCopy, parentIndex)
```

Which might be slightly more idiomatic, but I suspect there would be a negligible performance difference. Just documenting this.

2025-01-08 17:50 UTC, sangstar commented on runetree.go
> +	lastNodeMap := make([]int, 0)
Tiny nitpick again, but wouldn't this technically be a wasted allocation for `currentNodeIdx = 0`?

2025-02-11 16:33 UTC, sangstar requested changes
Just based on these changes, the only issue is the naming of the struct receiver method.

2025-02-11 16:33 UTC, sangstar commented on runetree.go
> +func (rt *RegexNode) createTree(AST *syntax.Regexp, ASTPath []string) {
There's an idiom in Go that says a struct receiver should be named as the lower-cased struct's acronym, so it should be named `rn`.

2025-02-13 14:31 UTC, wbrown commented on gpt_bpe.go
> +	norms := make([]string, 0)
@Rexwang8 @sangstar Please note for each comment resolved how it was resolved.

doing a huddle is not a substitute for documenting this interchange.

2025-04-23 13:23 UTC, wbrown approved these changes
:+1:

2025-04-23 13:24 UTC, merged